"""Initial migration

Revision ID: a1f72c9cdcb0
Revises:
Create Date: 2026-03-03 21:15:53.073217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1f72c9cdcb0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("create_on", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("xmind_version", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("converted_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "testcases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("preconditions", sa.String(), nullable=True),
        sa.Column("execution_type", sa.Integer(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("estimated_exec_duration", sa.Integer(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("product", sa.String(), nullable=True),
        sa.Column("suite", sa.String(), nullable=True),
        sa.Column("result", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("testcase_id", sa.Integer(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("actions", sa.String(), nullable=False),
        sa.Column("expectedresults", sa.String(), nullable=True),
        sa.Column("execution_type", sa.Integer(), nullable=False),
        sa.Column("result", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["testcase_id"], ["testcases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_steps")
    op.drop_table("testcases")
    op.drop_table("records")
    # ### end Alembic commands ###
